from enum import Enum


class Headers(Enum):
    TITLE = 'tytuł ogłoszenia'
    LINK = 'link'
    LOCATION = 'lokalizacja'
    M2 = 'powierzchnia'
    TOTAL_PRICE = 'cena'
    PRICE_PER_M2 = 'cena za metr'
    RENT = 'czynsz'
    ROOMS = 'liczba pokoi'
    BUILDING_TYPE = 'rodzaj budynku'
    MARKET = 'rynek'
    HEATING = 'ogrzewanie'
    FLOOR = 'piętro'
    FINISH_CONDITION = 'stan wykończenia'
    OWNERSHIP_FORM = 'forma własności'
    AVAILABLE_FROM = 'dostępne od'
    ADVERTISER_TYPE = 'typ ogłoszeniodawcy'
    ADDITIONAL_INFO = 'informacje dodatkowe'
    BUILDING_YEAR = 'rok budowy'
    ELEVATOR = 'winda'
    BUILDING_MATERIAL = 'materiał budynku'
    WINDOWS = 'okna'
    ENERGY_CERTIFICATE = 'certyfikat energetyczny'
    EQUIPMENT = 'wyposażenie'
    SECURITY = 'zabezpieczenia'
    MEDIA = 'media'
    SOURCE = 'źródło'